spring:
  datasource:
    url: jdbc:h2:file:./data/shortenerdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update

app:
  default-max-clicks: 20
  default-expiration-time: 12h
